version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: cw_7
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    container_name: celery_app
    command: celery -A Coursework_7_drf worker -l INFO --loglevel warning
    volumes:
      - celery_data:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_LOG_LEVEL=debug
    healthcheck:
      test: [ "CMD", "celery", "inspect", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  celery-beat:
    build: .
    container_name: celery_beat_app
    command: celery -A Coursework_7_drf beat -l info -S django --loglevel warning
    volumes:
      - celery_beat_data:/app
    depends_on:
       redis:
          condition: service_healthy
       celery:
          condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_LOG_LEVEL=debug

volumes:
  postgres_data:
  redis_data:
  celery_data:
  celery_beat_data: