# Generated by Django 4.2.3 on 2023-11-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=100, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.IntegerField(default=0, verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='признак публичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=100, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, verbose_name='вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
